export const EVENT_DETAILS: Record<string, any> = {
  Robowars: {
    title: "Robowars",
    description: "Bring your best bot to the fight!",
    participation: "Team (4–5 Members)",
    rounds: ["Knockout Battle", "Semi Final", "Grand Finale"],
    rules: ["Max weight 15kg", "No explosives", "4–5 members per team"],
    prize: ["🥇 ₹20,000", "🥈 ₹10,000", "🥉 ₹5,000"],
    schedule: ["March 20 – Registration Close", "March 28 – Battle Day"],
    contact: ["9876543210", "robotics@collegefest.com"],
  },
  "God Speed": {
    title: "God Speed",
    description: "Race against time with lightning-fast reflexes!",
    participation: "Team (2–3 Members)",
    rounds: ["Prelims", "Semi-Finals", "Finals"],
    rules: [
      "Time limit per round",
      "2–3 members per team",
      "No external tools allowed",
    ],
    prize: ["🥇 ₹15,000", "🥈 ₹8,000", "🥉 ₹3,000"],
    schedule: ["March 21 – Registration Close", "March 27 – Event Day"],
    contact: ["9876543211", "godspeed@collegefest.com"],
  },
  "Robo Race": {
    title: "Robo Race",
    description: "Speed + control + precision",
    participation: "Team (3 Members)",
    rounds: ["Qualifiers", "Final Race"],
    rules: ["Max weight 10kg", "Autonomous bots only"],
    prize: ["🥇 ₹10,000", "🥈 ₹5,000"],
    schedule: ["March 22 – Qualifiers", "March 29 – Final"],
    contact: ["9123456780", "race@collegefest.com"],
  },
  RoboSoccer: {
    title: "RoboSoccer",
    description: "Robotic football championship!",
    participation: "Team (5 Members)",
    rounds: ["Group Stage", "Knockouts", "Finals"],
    rules: [
      "Each robot max 30cm x 30cm",
      "Max weight 2kg",
      "Autonomous operation",
    ],
    prize: ["🥇 ₹25,000", "🥈 ₹12,000", "🥉 ₹5,000"],
    schedule: ["March 15 – Registration Close", "March 26 – 27 – Tournament"],
    contact: ["9123456781", "soccer@collegefest.com"],
  },
  "Ultimate Line Tracer": {
    title: "Ultimate Line Tracer",
    description: "Follow the path with maximum speed!",
    participation: "Team (2 Members)",
    rounds: ["Qualifiers", "Finals"],
    rules: [
      "Bot must follow black line",
      "Max time 5 minutes",
      "No manual intervention",
    ],
    prize: ["🥇 ₹8,000", "🥈 ₹4,000", "🥉 ₹2,000"],
    schedule: ["March 19 – Registration Close", "March 25 – Event Day"],
    contact: ["9123456782", "linetracer@collegefest.com"],
  },
  Pacbot: {
    title: "Pacbot",
    description: "Navigate the maze like a pro!",
    participation: "Team (2–3 Members)",
    rounds: ["Qualifiers", "Semi-Finals", "Finals"],
    rules: ["Navigate automated maze", "Avoid obstacles", "Max time per round"],
    prize: ["🥇 ₹12,000", "🥈 ₹6,000", "🥉 ₹3,000"],
    schedule: ["March 18 – Registration Close", "March 24 – Event Day"],
    contact: ["9123456783", "pacbot@collegefest.com"],
  },
  Micromouse: {
    title: "Micromouse",
    description: "Solve the maze in minimum time!",
    participation: "Team (2–3 Members)",
    rounds: ["Maze Run", "Speed Run"],
    rules: [
      "Robot must solve maze independently",
      "Size limit 25cm x 25cm",
      "Max weight 500g",
    ],
    prize: ["🥇 ₹10,000", "🥈 ₹5,000", "🥉 ₹2,500"],
    schedule: ["March 17 – Registration Close", "March 23 – Event Day"],
    contact: ["9123456784", "micromouse@collegefest.com"],
  },
};

export const EVENTS_CATEGORIES = {
  Robotics: {
    label: "ROBOTICS EVENTS",
    description:
      "Dive into robotics competitions designed to test innovation, speed, and intelligence.",
    events: [
      "Robowars",
      "God Speed",
      "Robo Race",
      "RoboSoccer",
      "Ultimate Line Tracer",
      "Pacbot",
      "Micromouse",
    ],
  },
  Coding: {
    label: "CODING EVENTS",
    description:
      "Showcase your programming skills through logic, speed, and problem-solving challenges.",
    events: [
      "Code Hunt",
      "Debug It",
      "Hack Sprint",
      "Algo Master",
      "Blind Coding",
      "Tech Quiz",
      "Code Relay",
    ],
  },
  Electronics: {
    label: "ELECTRONICS EVENTS",
    description: "Test your circuit design and hardware problem-solving skills.",
    events: [
      "Circuitrix",
      "ElectroQuest",
      "PCB Design",
      "Component Hunt",
      "Signal Sprint",
      "Hardware Debug",
      "Electro Quiz",
    ],
  },
  Extravaganza: {
    label: "EXTRAVAGANZA EVENTS",
    description: "Fun, creativity, and excitement-packed technical challenges.",
    events: [
      "Tech Treasure Hunt",
      "Funathon",
      "Mystery Box",
      "Innovation Jam",
      "Brain Storm",
      "Rapid Fire",
      "Surprise Event",
    ],
  },
  Management: {
    label: "MANAGEMENT EVENTS",
    description:
      "Leadership, strategy, and business decision-making challenges.",
    events: [
      "Biz Plan",
      "Marketing Mania",
      "Case Study",
      "HR Hunt",
      "Startup Pitch",
      "Finance Frenzy",
      "Management Quiz",
    ],
  },
  Engineering: {
    label: "ENGINEERING EVENTS",
    description: "Core engineering challenges across disciplines.",
    events: [
      "Bridge Builder",
      "CAD Clash",
      "Mechathon",
      "Design Sprint",
      "Civil Draft",
      "Tech Expo",
      "Build-a-thon",
    ],
  },
  Quiz: {
    label: "QUIZ EVENTS",
    description: "Test your technical and general knowledge under pressure.",
    events: [
      "Tech Quiz",
      "General Quiz",
      "Rapid Fire",
      "Visual Quiz",
      "Logic Quiz",
      "Surprise Round",
      "Final Showdown",
    ],
  },
  Online: {
    label: "ONLINE EVENTS",
    description: "Compete remotely in exciting online challenges.",
    events: [
      "Online Coding",
      "Virtual Quiz",
      "Remote Hackathon",
      "AI Challenge",
      "Web Design",
      "Online Debate",
      "E-Sports Tech",
    ],
  },
};
